### ISSUE TITLE
Dotnet Core 2.0 support. 

### ISSUE THREAD

**Issue by mateuszlewko** [dungpa/Z3Fs#4]
Is it possible to use Z3Fs with dotnet core 2.0 project? I've tried to do it on my own, but I'm having `DllNotFoundException`:
> Unhandled Exception: System.TypeInitializationException: The type initializer for '<StartupCode$FsZ3>.$Microsoft.Z3.Api' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libz3.dll': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Z3.Native.LIB.Z3_mk_config()
   at Microsoft.Z3.Context..ctor(Dictionary`2 settings)
   at <StartupCode$FsZ3>.$Microsoft.Z3.Api..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Z3.Int.Int(String s)
   at <StartupCode$MyProj>.$Program.main@() in /home/mateuszlewko/Workspace/Projects/FsZ3/src/Examples/MyProj/Program.fs:line 12
[1]    16601 abort (core dumped)  ./MyProj

It works fine with mono.

**Comment by normanhh3** [comment]
Likely the dotnet wrapper for Z3 needs to be updated to work with core.  Looks like work is being done here: https://github.com/Z3Prover/z3/issues/1423
